// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyKhachSan_UNETI06_TI17A4HN.Data;

#nullable disable

namespace QuanLyKhachSan_UNETI06_TI17A4HN.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyKhachSan_UNETI06_TI17A4HN.Models.ChiTietDatPhong", b =>
                {
                    b.Property<int>("MaPhieuDat")
                        .HasColumnType("int");

                    b.Property<int>("MaPhong")
                        .HasColumnType("int");

                    b.Property<decimal>("DonGiaDem")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SoDem")
                        .HasColumnType("int");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaPhieuDat", "MaPhong");

                    b.HasIndex("MaPhong");

                    b.ToTable("ChiTietDatPhongs");
                });

            modelBuilder.Entity("QuanLyKhachSan_UNETI06_TI17A4HN.Models.KhachHang", b =>
                {
                    b.Property<int>("MaKhachHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKhachHang"));

                    b.Property<string>("CCCD")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaTaiKhoan")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaKhachHang");

                    b.HasIndex("CCCD")
                        .IsUnique();

                    b.HasIndex("MaTaiKhoan")
                        .IsUnique();

                    b.ToTable("KhachHangs");
                });

            modelBuilder.Entity("QuanLyKhachSan_UNETI06_TI17A4HN.Models.LoaiPhong", b =>
                {
                    b.Property<int>("MaLoaiPhong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoaiPhong"));

                    b.Property<decimal>("DonGiaDem")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoNguoiToiDa")
                        .HasColumnType("int");

                    b.Property<string>("TenLoaiPhong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaLoaiPhong");

                    b.HasIndex("TenLoaiPhong")
                        .IsUnique();

                    b.ToTable("LoaiPhongs");
                });

            modelBuilder.Entity("QuanLyKhachSan_UNETI06_TI17A4HN.Models.PhieuDatPhong", b =>
                {
                    b.Property<int>("MaPhieuDat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhieuDat"));

                    b.Property<int>("MaKhachHang")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayNhanDuKien")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTraDuKien")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TongTienDuKien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaPhieuDat");

                    b.HasIndex("MaKhachHang");

                    b.ToTable("PhieuDatPhongs");
                });

            modelBuilder.Entity("QuanLyKhachSan_UNETI06_TI17A4HN.Models.Phong", b =>
                {
                    b.Property<int>("MaPhong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhong"));

                    b.Property<decimal>("DonGiaDem")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaLoaiPhong")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoPhong")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Tang")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaPhong");

                    b.HasIndex("MaLoaiPhong");

                    b.HasIndex("SoPhong")
                        .IsUnique();

                    b.ToTable("Phongs");
                });

            modelBuilder.Entity("QuanLyKhachSan_UNETI06_TI17A4HN.Models.TaiKhoan", b =>
                {
                    b.Property<int>("MaTaiKhoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTaiKhoan"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaTaiKhoan");

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.ToTable("TaiKhoans");
                });

            modelBuilder.Entity("QuanLyKhachSan_UNETI06_TI17A4HN.Models.ChiTietDatPhong", b =>
                {
                    b.HasOne("QuanLyKhachSan_UNETI06_TI17A4HN.Models.PhieuDatPhong", "PhieuDatPhong")
                        .WithMany("ChiTietDatPhongs")
                        .HasForeignKey("MaPhieuDat")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyKhachSan_UNETI06_TI17A4HN.Models.Phong", "Phong")
                        .WithMany("ChiTietDatPhongs")
                        .HasForeignKey("MaPhong")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PhieuDatPhong");

                    b.Navigation("Phong");
                });

            modelBuilder.Entity("QuanLyKhachSan_UNETI06_TI17A4HN.Models.KhachHang", b =>
                {
                    b.HasOne("QuanLyKhachSan_UNETI06_TI17A4HN.Models.TaiKhoan", "TaiKhoan")
                        .WithOne("KhachHang")
                        .HasForeignKey("QuanLyKhachSan_UNETI06_TI17A4HN.Models.KhachHang", "MaTaiKhoan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("QuanLyKhachSan_UNETI06_TI17A4HN.Models.PhieuDatPhong", b =>
                {
                    b.HasOne("QuanLyKhachSan_UNETI06_TI17A4HN.Models.KhachHang", "KhachHang")
                        .WithMany("PhieuDatPhongs")
                        .HasForeignKey("MaKhachHang")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("QuanLyKhachSan_UNETI06_TI17A4HN.Models.Phong", b =>
                {
                    b.HasOne("QuanLyKhachSan_UNETI06_TI17A4HN.Models.LoaiPhong", "LoaiPhong")
                        .WithMany("Phongs")
                        .HasForeignKey("MaLoaiPhong")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LoaiPhong");
                });

            modelBuilder.Entity("QuanLyKhachSan_UNETI06_TI17A4HN.Models.KhachHang", b =>
                {
                    b.Navigation("PhieuDatPhongs");
                });

            modelBuilder.Entity("QuanLyKhachSan_UNETI06_TI17A4HN.Models.LoaiPhong", b =>
                {
                    b.Navigation("Phongs");
                });

            modelBuilder.Entity("QuanLyKhachSan_UNETI06_TI17A4HN.Models.PhieuDatPhong", b =>
                {
                    b.Navigation("ChiTietDatPhongs");
                });

            modelBuilder.Entity("QuanLyKhachSan_UNETI06_TI17A4HN.Models.Phong", b =>
                {
                    b.Navigation("ChiTietDatPhongs");
                });

            modelBuilder.Entity("QuanLyKhachSan_UNETI06_TI17A4HN.Models.TaiKhoan", b =>
                {
                    b.Navigation("KhachHang");
                });
#pragma warning restore 612, 618
        }
    }
}
